name: lyrebird
description: Visual editor for .ARB localization files to be used with the intl package.
version: 0.1.0
homepage:

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:

dev_dependencies:
