name: lyrebird
description: Visual editor for Application Resuorce Bundle localization files to be used with the intl package.
version: 0.1.0
homepage:

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  archive: ^3.3.5
  args: ^2.3.1

dev_dependencies: 
  lints: ^2.0.1
